import { FC } from 'react';

type Stage = {
  name: string;
  sub: string;
  meta: string;
  metaClass?: string;
  state: 'done' | 'run' | 'queued';
};

const STAGES: Stage[] = [
  {
    name: 'Prompt → app',
    sub: 'Generated by AI assistant · reviewed',
    meta: 'ready',
    metaClass: 'text-[var(--lo-green)]',
    state: 'done',
  },
  {
    name: 'Build & package',
    sub: 'Reproducible image · SBOM attached',
    meta: '1m 12s',
    metaClass: 'text-[var(--lo-green)]',
    state: 'done',
  },
  {
    name: 'Security scan',
    sub: 'Deps, secrets & policy — 0 criticals',
    meta: 'passed',
    metaClass: 'text-[var(--lo-green)]',
    state: 'done',
  },
  {
    name: 'Ship to private cloud',
    sub: 'Namespace provisioned · TLS & DNS wired',
    meta: '98%',
    metaClass: 'text-[var(--lo-cyan)]',
    state: 'run',
  },
  {
    name: 'Audit & observe',
    sub: 'Logs, metrics & trail — on by default',
    meta: 'queued',
    state: 'queued',
  },
];

const nodeClasses = (state: Stage['state']) => {
  if (state === 'done')
    return 'border-[var(--lo-accent)] text-[var(--lo-accent)] shadow-[0_0_14px_-3px_var(--lo-accent)]';
  if (state === 'run')
    return 'border-[var(--lo-cyan)] text-[var(--lo-cyan)]';
  return 'border-[var(--lo-line)] text-[var(--lo-fg-dim)]';
};

/**
 * Illustrative deploy pipeline. The stage timings/values are placeholder UI
 * to make the console feel live — not real telemetry.
 */
const Console: FC = () => {
  return (
    <div
      className="lo-mono relative z-2 overflow-hidden rounded-[14px] border border-[var(--lo-line)] bg-[linear-gradient(180deg,var(--lo-surface-2),var(--lo-surface))] text-[13px] shadow-[var(--lo-shadow-lg)]"
      role="img"
      aria-label="Deployment pipeline: prompt built, image built and scanned, guardrails passed, shipping to your private cloud, audit and observability queued."
    >
      <div className="flex items-center gap-2 border-b border-[var(--lo-line-soft)] px-[15px] py-3 text-[var(--lo-fg-dim)]">
        <span className="h-2.5 w-2.5 rounded-full bg-[var(--lo-line)]" />
        <span className="h-2.5 w-2.5 rounded-full bg-[var(--lo-line)]" />
        <span className="h-2.5 w-2.5 rounded-full bg-[var(--lo-accent)]" />
        <span className="ml-2 tracking-[0.03em]">
          <b className="font-medium text-[var(--lo-fg-mut)]">low-ops</b> /
          golden-path · <b className="font-medium text-[var(--lo-fg-mut)]">prod</b>
        </span>
        <span className="ml-auto inline-flex items-center gap-2 text-[11px] text-[var(--lo-cyan)]">
          <span className="lo-blink h-[7px] w-[7px] rounded-full bg-[var(--lo-cyan)]" />
          deploying
        </span>
      </div>

      <div className="px-[18px] pt-5 pb-2">
        {STAGES.map((stage, i) => (
          <div
            key={stage.name}
            className="relative grid grid-cols-[26px_1fr_auto] items-start gap-3 py-[9px]"
          >
            {i > 0 && (
              <span
                className={`absolute left-3 -top-[9px] h-[18px] w-0.5 ${
                  STAGES[i - 1].state === 'done'
                    ? 'bg-[var(--lo-accent)]'
                    : 'bg-[var(--lo-line)]'
                }`}
              />
            )}
            <span
              className={`grid h-6 w-6 place-items-center rounded-[7px] border bg-[var(--lo-ink-2)] text-[12px] ${nodeClasses(stage.state)}`}
            >
              {stage.state === 'done' ? (
                '✓'
              ) : stage.state === 'run' ? (
                <span className="lo-spin">◠</span>
              ) : (
                '·'
              )}
            </span>
            <span>
              <span className="block text-[var(--lo-fg)]">{stage.name}</span>
              <span className="mt-0.5 block text-[11.5px] text-[var(--lo-fg-dim)]">
                {stage.sub}
              </span>
            </span>
            <span
              className={`whitespace-nowrap pt-[3px] text-right text-[11px] ${stage.metaClass ?? 'text-[var(--lo-fg-dim)]'}`}
            >
              {stage.meta}
            </span>
          </div>
        ))}
      </div>

      <div className="mt-2 flex items-center justify-between gap-3 border-t border-[var(--lo-line-soft)] px-[18px] py-[13px] text-[12px] text-[var(--lo-fg-mut)]">
        <span>guardrails enforced automatically</span>
        <span className="text-[var(--lo-accent)]">▲ golden path</span>
      </div>
    </div>
  );
};

export default Console;
